// apps/checkout/src/app/app.tsx
import styled from 'styled-components';
import { store } from '@org/state-manager';

import NxWelcome from './nx-welcome';

const StyledApp = styled.div`
  // Your style here
`;

export function App() {
  store.subscribe(() => {
    console.log('aaa state in react', store.getState());
  });

  const handleIncrement = () => {
    store.dispatch({ type: 'INCREMENT' });
  };

  return (
    <StyledApp>
      <button onClick={handleIncrement}>Increment</button>
      <NxWelcome title="checkout" />
    </StyledApp>
  );
}

export default App;

// shell/src/app/app.component.ts
import { Component, AfterViewInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NxWelcomeComponent } from './nx-welcome.component';
import { CheckoutWrapperComponent } from './checkout-wrapper/checkout-wrapper.component';
import { store } from '@org/state-manager';

@Component({
  standalone: true,
  imports: [NxWelcomeComponent, RouterModule, CheckoutWrapperComponent],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.sass',
})
export class AppComponent implements AfterViewInit {
  async ngAfterViewInit() {
    store.subscribe(() => {
      console.log('aaa state in shell', store.getState());
    });
  }

  public decrement() {
    store.dispatch({ type: 'DECREMENT' });
  }

  title = 'shell 2';
}

<ul class="remote-menu">
  <li><a routerLink="/">Home</a></li>
  <li><a routerLink="shop">Shop</a></li>
  <li><a routerLink="cart">Cart</a></li>
  <li><a routerLink="warehouse">Warehouse</a></li>
</ul>
<div>
  <button (click)="decrement()">decrement</button>
  <app-checkout-wrapper></app-checkout-wrapper>
</div>
<router-outlet></router-outlet>
